name: Release

on:
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          (cp LICENSE _Heap/LICENSE && cd _Heap && zip -r ../_Heap.zip .)
          (cp LICENSE Heap/LICENSE && cd Heap && zip -r ../Heap.zip .)
          (cp LICENSE HeapCollector/LICENSE && cd HeapCollector && zip -r ../HeapCollector.zip .)
          (cp LICENSE HeapExecutor/LICENSE && cd HeapExecutor && zip -r ../HeapExecutor.zip .)
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            _Heap.zip
            Heap.zip
            HeapCollector.zip
            HeapExecutor.zip
