name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: mcenv/setup-minecraft@main
        with:
          version: "1.18.1"
      - id: minecraft
        run: |
          cp -r _Heap/* world/datapacks/_Heap/
          cp -r Heap/* world/datapacks/Heap/
          cp -r Tests/* world/datapacks/Tests/

          echo "eula=true" > eula.txt

          cat << EOF > server.properties
          snooper-enabled=false
          function-permission-level=4
          max-tick-time=-1
          max-players=0
          EOF

          minecraft
      - run: exit ${{ steps.minecraft.outputs.status }}
